/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "style": {
    name: "style",
    description: "",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "chart": {
    name: "chart",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "registry/simplifying-ai/ui/charts/chart-config.ts",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/simplifying-ai/ui/charts/chart-container.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/simplifying-ai/ui/charts/chart-axis.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/simplifying-ai/ui/charts/chart-grid.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/simplifying-ai/ui/charts/chart-tooltip.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/simplifying-ai/ui/charts/chart-legend.tsx",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/simplifying-ai/ui/charts/chart-utils.ts",
      type: "registry:ui",
      target: ""
    },{
      path: "registry/simplifying-ai/ui/charts/index.ts",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/chart-config.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "line-chart": {
    name: "line-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/basic/line-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/basic/line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart": {
    name: "bar-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/basic/bar-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/basic/bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart": {
    name: "area-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/basic/area-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/basic/area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scatter-chart": {
    name: "scatter-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/basic/scatter-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/basic/scatter-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pie-chart": {
    name: "pie-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/basic/pie-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/basic/pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "donut-chart": {
    name: "donut-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/basic/donut-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/basic/donut-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "histogram-chart": {
    name: "histogram-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/statistical/histogram-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/statistical/histogram-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "box-plot-chart": {
    name: "box-plot-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/statistical/box-plot-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/statistical/box-plot-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "violin-chart": {
    name: "violin-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/statistical/violin-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/statistical/violin-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "candlestick-chart": {
    name: "candlestick-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/financial/candlestick-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/financial/candlestick-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waterfall-chart": {
    name: "waterfall-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/financial/waterfall-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/financial/waterfall-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart": {
    name: "funnel-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/financial/funnel-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/financial/funnel-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "heatmap-chart": {
    name: "heatmap-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/scientific/heatmap-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/scientific/heatmap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "contour-chart": {
    name: "contour-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/scientific/contour-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/scientific/contour-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radar-chart": {
    name: "radar-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/specialized/radar-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/specialized/radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "treemap-chart": {
    name: "treemap-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/specialized/treemap-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/specialized/treemap-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sunburst-chart": {
    name: "sunburst-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/specialized/sunburst-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/specialized/sunburst-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sankey-chart": {
    name: "sankey-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/specialized/sankey-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/specialized/sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart": {
    name: "gauge-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/specialized/gauge-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/specialized/gauge-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart": {
    name: "choropleth-chart",
    description: "",
    type: "registry:ui",
    registryDependencies: ["chart"],
    files: [{
      path: "registry/simplifying-ai/ui/charts/maps/choropleth-chart.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/ui/charts/maps/choropleth-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    files: [{
      path: "registry/simplifying-ai/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/hooks/use-mobile.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart-demo": {
    name: "area-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["area-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/area-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/area-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart-smooth-demo": {
    name: "area-chart-smooth-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["area-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/area-chart-smooth-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/area-chart-smooth-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart-step-demo": {
    name: "area-chart-step-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["area-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/area-chart-step-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/area-chart-step-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart-multi-demo": {
    name: "area-chart-multi-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["area-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/area-chart-multi-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/area-chart-multi-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-demo": {
    name: "bar-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-label-demo": {
    name: "bar-chart-label-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-label-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-label-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-horizontal-demo": {
    name: "bar-chart-horizontal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-horizontal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-horizontal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-multiple-demo": {
    name: "bar-chart-multiple-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-multiple-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-multiple-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-stacked-demo": {
    name: "bar-chart-stacked-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-stacked-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-stacked-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-negative-demo": {
    name: "bar-chart-negative-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-negative-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-negative-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-interactive-demo": {
    name: "bar-chart-interactive-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-interactive-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-interactive-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-mixed-demo": {
    name: "bar-chart-mixed-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-mixed-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-mixed-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart-active-demo": {
    name: "bar-chart-active-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["bar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/bar-chart-active-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/bar-chart-active-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "line-chart-demo": {
    name: "line-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["line-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/line-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/line-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "scatter-chart-demo": {
    name: "scatter-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["scatter-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/scatter-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/scatter-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pie-chart-demo": {
    name: "pie-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["pie-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/pie-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/pie-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "donut-chart-demo": {
    name: "donut-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["donut-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/donut-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/donut-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "donut-chart-gradient-demo": {
    name: "donut-chart-gradient-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["donut-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/donut-chart-gradient-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/donut-chart-gradient-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "donut-chart-separated-demo": {
    name: "donut-chart-separated-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["donut-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/donut-chart-separated-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/donut-chart-separated-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "donut-chart-half-demo": {
    name: "donut-chart-half-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["donut-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/donut-chart-half-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/donut-chart-half-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "histogram-chart-demo": {
    name: "histogram-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["histogram-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/histogram-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/histogram-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "box-plot-chart-demo": {
    name: "box-plot-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["box-plot-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/box-plot-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/box-plot-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "box-plot-chart-horizontal-demo": {
    name: "box-plot-chart-horizontal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["box-plot-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/box-plot-chart-horizontal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/box-plot-chart-horizontal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "box-plot-chart-multi-demo": {
    name: "box-plot-chart-multi-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["box-plot-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/box-plot-chart-multi-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/box-plot-chart-multi-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "box-plot-chart-comparison-demo": {
    name: "box-plot-chart-comparison-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["box-plot-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/box-plot-chart-comparison-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/box-plot-chart-comparison-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "box-plot-chart-outliers-demo": {
    name: "box-plot-chart-outliers-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["box-plot-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/box-plot-chart-outliers-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/box-plot-chart-outliers-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "violin-chart-demo": {
    name: "violin-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["violin-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/violin-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/violin-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "candlestick-chart-demo": {
    name: "candlestick-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["candlestick-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/candlestick-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/candlestick-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "candlestick-chart-hollow-demo": {
    name: "candlestick-chart-hollow-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["candlestick-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/candlestick-chart-hollow-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/candlestick-chart-hollow-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "candlestick-chart-scrollable-demo": {
    name: "candlestick-chart-scrollable-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["candlestick-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/candlestick-chart-scrollable-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/candlestick-chart-scrollable-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "waterfall-chart-demo": {
    name: "waterfall-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["waterfall-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/waterfall-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/waterfall-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart-demo": {
    name: "funnel-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["funnel-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/funnel-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/funnel-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart-gradient-demo": {
    name: "funnel-chart-gradient-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["funnel-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/funnel-chart-gradient-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/funnel-chart-gradient-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart-flat-demo": {
    name: "funnel-chart-flat-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["funnel-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/funnel-chart-flat-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/funnel-chart-flat-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart-pyramid-demo": {
    name: "funnel-chart-pyramid-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["funnel-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/funnel-chart-pyramid-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/funnel-chart-pyramid-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "funnel-chart-horizontal-demo": {
    name: "funnel-chart-horizontal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["funnel-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/funnel-chart-horizontal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/funnel-chart-horizontal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "heatmap-chart-demo": {
    name: "heatmap-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["heatmap-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/heatmap-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/heatmap-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "contour-chart-demo": {
    name: "contour-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["contour-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/contour-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/contour-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "contour-chart-lines-demo": {
    name: "contour-chart-lines-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["contour-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/contour-chart-lines-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/contour-chart-lines-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "contour-chart-thermal-demo": {
    name: "contour-chart-thermal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["contour-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/contour-chart-thermal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/contour-chart-thermal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "contour-chart-scatter-demo": {
    name: "contour-chart-scatter-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["contour-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/contour-chart-scatter-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/contour-chart-scatter-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radar-chart-demo": {
    name: "radar-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["radar-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/radar-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/radar-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "treemap-chart-demo": {
    name: "treemap-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["treemap-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/treemap-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/treemap-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sunburst-chart-demo": {
    name: "sunburst-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["sunburst-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/sunburst-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/sunburst-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-demo": {
    name: "gauge-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-speedometer-demo": {
    name: "gauge-chart-speedometer-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-speedometer-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-speedometer-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-segmented-demo": {
    name: "gauge-chart-segmented-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-segmented-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-segmented-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-radial-demo": {
    name: "gauge-chart-radial-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-radial-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-radial-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-minimal-demo": {
    name: "gauge-chart-minimal-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-minimal-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-minimal-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-gradient-demo": {
    name: "gauge-chart-gradient-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-gradient-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-gradient-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-meter-demo": {
    name: "gauge-chart-meter-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-meter-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-meter-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "gauge-chart-dashboard-demo": {
    name: "gauge-chart-dashboard-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["gauge-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/gauge-chart-dashboard-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/gauge-chart-dashboard-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart-demo": {
    name: "choropleth-chart-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["choropleth-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/choropleth-chart-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/choropleth-chart-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart-usa-demo": {
    name: "choropleth-chart-usa-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["choropleth-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/choropleth-chart-usa-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/choropleth-chart-usa-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart-china-demo": {
    name: "choropleth-chart-china-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["choropleth-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/choropleth-chart-china-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/choropleth-chart-china-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart-uk-demo": {
    name: "choropleth-chart-uk-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["choropleth-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/choropleth-chart-uk-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/choropleth-chart-uk-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart-germany-demo": {
    name: "choropleth-chart-germany-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["choropleth-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/choropleth-chart-germany-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/choropleth-chart-germany-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart-france-demo": {
    name: "choropleth-chart-france-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["choropleth-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/choropleth-chart-france-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/choropleth-chart-france-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "choropleth-chart-brazil-demo": {
    name: "choropleth-chart-brazil-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["choropleth-chart"],
    files: [{
      path: "registry/simplifying-ai/examples/choropleth-chart-brazil-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/simplifying-ai/examples/choropleth-chart-brazil-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }